---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Season of mists and mellow fruitfulness,  
   Close bosom-friend of the maturing sun;  
Conspiring with him how to load and bless  
   With fruit the vines that round the thatch-eves run;  
To bend with apples the moss'd cottage-trees,  
   And fill all fruit with ripeness to the core;  
      To swell the gourd, and plump the hazel shells  
   With a sweet kernel; to set budding more,  
And still more, later flowers for the bees,  
Until they think warm days will never cease,  
      For summer has o'er-brimm'd their clammy cells.  

Who hath not seen thee oft amid thy store?  
   Sometimes whoever seeks abroad may find  
Thee sitting careless on a granary floor,  
   Thy hair soft-lifted by the winnowing wind;  
Or on a half-reap'd furrow sound asleep,  
   Drows'd with the fume of poppies, while thy hook  
      Spares the next swath and all its twined flowers:  
And sometimes like a gleaner thou dost keep  
   Steady thy laden head across a brook;  
